config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :items, only: [ :index, :show ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :selections, only: [:create, :index, :destroy]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :items, only: [ :show, :create ]
    end
  end
end

app/models/selection.rb
# frozen_string_literal: true

class Selection < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/controllers/selections_controller.rb
# frozen_string_literal: true

class SelectionsController < ApplicationController
  # skip_before_action :authenticate_user!, only: :create
  skip_before_action :verify_authenticity_token, only: :create
  before_action :set_selection, only: [:destroy]

  def index
    @selection_pool = Selection.joins(:item).where(user: current_user)
    @categories = Item.joins(:selections).where(selections: {user: current_user }).pluck(:category).uniq
    @selections = @selection_pool
    if params[:item].present?
      terms = params[:item].keys
      @selections = terms.map do |term|
        @selection_pool.where('items.category = :query', query: term)
      end.reduce(:|)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @selection = Selection.new()
    @selection.user = current_user
    @selection.item = Item.find(params[:item_id])
    @selection.save
  end

  def destroy
    @selection.destroy
    respond_to do |format|
      format.html { redirect_to selections_path }
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end
  end
  private

  def set_selection
    @selection = Selection.find(params[:id])
  end
end

app/views/selections/_item_card.html.erb
<div class="item" data-selection-id="<%= selection.id %>">
  <%= link_to selection_path(selection), method: :delete, class: "cancel abs-right-top cross", remote: true do %>
    +
  <% end %>
  <div class="item-image">
    <%= link_to selection.item.url, target: "_blank" do %>
      <%= image_tag selection.item.photo, class: "item-image" %>
    <% end %>
  </div>
  <div class="item-description">
    <div class="first-line">
      <%= link_to selection.item.url, class: "title-item", target: "_blank" do %>
        <h2><%= selection.item.title %></h2>
      <% end %>
    </div>
    <h5><%= selection.item.price %>€</h5>
    <div class="impact-description">

      <section>
        <div class="impact-detail-description">
          <p><strong><i class="fa fa-globe" aria-hidden="true"></i> CLIMATE</strong></p>
          <div class="scores">
            <% if selection.item.calcul_climate_impact > 15 %>
              <div class="arrow">
                <div class="arrow arrow-status <%= selection.item.color_climate %> " style="width: <%= (selection.item.calcul_climate_impact).to_i %>%">
                  <p><%= (selection.item.calcul_climate).round(2) %> kg éq. CO2</p>
                  <span class="arrow-pointer"></span>
                </div>
              </div>
            <% else %>
              <div class="arrow">
                <div class="arrow arrow-status <%= selection.item.color_climate %> " style="width: <%= (selection.item.calcul_climate_impact).to_i %>%">
                 <span class="arrow-pointer"></span>
                </div>
                <p style="margin-left: 5px;"><%= selection.item.calcul_climate %> kg éq. CO2</p>
              </div>
            <% end %>

          </div>
        </div>

        <div class="impact-detail-description">
          <p><strong><i class="fa fa-tint" aria-hidden="true"></i> WATER </strong></p>
          <div class="scores">
            <% if selection.item.calcul_water_impact > 15 %>
              <div class="arrow">
                <div class="arrow arrow-status <%= selection.item.color_water %> " style="width: <%= (selection.item.calcul_water_impact).to_i %>%">
                  <p><%= (selection.item.calcul_water).round(2) %> g éq. P</p>
                  <span class="arrow-pointer"></span>
                </div>
              </div>
            <% else %>
              <div class="arrow">
                <div class="arrow arrow-status <%= selection.item.color_water %> " style="width: <%= (selection.item.calcul_water_impact).to_i %>%">
                  <span class="arrow-pointer"></span>
                </div>
                <p style="margin-left: 5px;"><%= (selection.item.calcul_water_impact).round(2) %> g éq. P</p>
              </div>
            <% end %>

          </div>
        </div>

        <div class="impact-detail-description">
          <p><strong><i class="fa fa-cloud" aria-hidden="true"></i> AIR </strong></p>
          <div class="scores">
            <% if selection.item.calcul_climate_impact > 15 %>
              <div class="arrow">
                <div class="arrow arrow-status <%= selection.item.color_air %> " style="width: <%= (selection.item.calcul_air_impact).to_i %>%">
                  <p><%= (selection.item.calcul_air).round(2) %> mol éq. H+</p>
                  <span class="arrow-pointer"></span>
                </div>
              </div>
            <% else %>
              <div class="arrow">
                <div class="arrow arrow-status <%= selection.item.color_air %> " style="width: <%= (selection.item.calcul_air_impact).to_i %>%">
                  <span class="arrow-pointer"></span>
                </div>
                <p style="margin-left: 5px;"><%= selection.item.calcul_air_impact %> mol éq. H+</p>
              </div>
            <% end %>

          </div>
        </div>
      </section>
      <div class="total-score <%= selection.item.color_total %>">
        <h1> <%= (selection.item.total_impact).to_i %> </h1>
        <p>/ 100</p>
      </div>
    </div>
  </div>
</div>

app/views/selections/destroy.js.erb
document.querySelector("[data-selection-id='<%= @selection.id %>']").remove();

app/views/selections/index.html.erb
<div class="selections">
  <div class="left-nav-container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <div class="form-post">
          <h2>Find in your selection by</h2>
          <%= form_tag("/selections", method: 'get', class: "form-stuff", remote: true) do %>
            <div class="form-group">
              <div class="category-choices">
                <% @categories.each do |category| %>
                  <input type="checkbox" class="hidden" name="item[<%= category %>]" id="<%= category %>">
                  <label for="<%= category %>" class="category-choice"><%= category.capitalize %> <i class="fa fa-check"></i></label>
                <% end %>
              </div>
            </div>
            <input type="submit" class="hidden" value="Reload"></input>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="container-selections">
    <div id="all_items">
      <% @selections.reverse_each do |selection| %>
        <%= render 'selections/item_card', selection: selection %>
      <% end %>
    </div>
  </div>
</div>

app/views/selections/index.js.erb
var cards = document.querySelector("#all_items")
cards.innerHTML = ""

<% @selections.each do |selection| %>
  cards.insertAdjacentHTML("beforeend", "<%= j render 'selections/item_card', selection: selection %>")
<% end %>